/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './users.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from './users-routing.module';
import * as import5 from './users.component.ngfactory';
import * as import6 from './users.component';
class UsersModuleInjector extends import0.ɵNgModuleInjector<import1.UsersModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _UsersRoutingModule_2:import4.UsersRoutingModule;
  _UsersModule_3:import1.UsersModule;
  __NgLocalization_4:import2.NgLocaleLocalization;
  _ROUTES_5:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import5.UsersComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_4():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_4;
  }
  createInternal():import1.UsersModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ɵa,(null as any)),this.parent.get(import3.Router,(null as any)));
    this._UsersRoutingModule_2 = new import4.UsersRoutingModule();
    this._UsersModule_3 = new import1.UsersModule();
        this._ROUTES_5 = [[{
          path: '',
          component: import6.UsersComponent
        }
    ]];
    return this._UsersModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.UsersRoutingModule)) { return this._UsersRoutingModule_2; }
    if ((token === import1.UsersModule)) { return this._UsersModule_3; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import3.ROUTES)) { return this._ROUTES_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const UsersModuleNgFactory:import0.NgModuleFactory<import1.UsersModule> = new import0.NgModuleFactory<any>(UsersModuleInjector,import1.UsersModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvRGllZ28vRGVza3RvcC9hbmd1bGFyQ291cnNlL25vLWNsaWVudC1wcm9qZWN0L3NyYy9hcHAvdXNlcnMvdXNlcnMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0RpZWdvL0Rlc2t0b3AvYW5ndWxhckNvdXJzZS9uby1jbGllbnQtcHJvamVjdC9zcmMvYXBwL3VzZXJzL3VzZXJzLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
