/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './users.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './users.component';
const styles_UsersComponent:any[] = [import0.styles];
export const RenderType_UsersComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_UsersComponent,
  data: {}
}
);
export function View_UsersComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Users Component']))
  ]
  ,(null as any),(null as any));
}
function View_UsersComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_UsersComponent_0,RenderType_UsersComponent)),
    import1.ɵdid(49152,(null as any),0,import2.UsersComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UsersComponentNgFactory:import1.ComponentFactory<import2.UsersComponent> = import1.ɵccf('ng-component',import2.UsersComponent,View_UsersComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvRGllZ28vRGVza3RvcC9hbmd1bGFyQ291cnNlL25vLWNsaWVudC1wcm9qZWN0L3NyYy9hcHAvdXNlcnMvdXNlcnMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0RpZWdvL0Rlc2t0b3AvYW5ndWxhckNvdXJzZS9uby1jbGllbnQtcHJvamVjdC9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL0RpZWdvL0Rlc2t0b3AvYW5ndWxhckNvdXJzZS9uby1jbGllbnQtcHJvamVjdC9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvRGllZ28vRGVza3RvcC9hbmd1bGFyQ291cnNlL25vLWNsaWVudC1wcm9qZWN0L3NyYy9hcHAvdXNlcnMvdXNlcnMuY29tcG9uZW50LnRzLlVzZXJzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPlVzZXJzIENvbXBvbmVudDwvaDE+IiwiPG5nLWNvbXBvbmVudD48L25nLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUk7Ozs7OztJQ0FKO2dCQUFBOzs7OyJ9
