/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './home.component';
const styles_HomeComponent:any[] = ([] as any[]);
export const RenderType_HomeComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_HomeComponent,
  data: {}
}
);
export function View_HomeComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['The home page']))
  ]
  ,(null as any),(null as any));
}
function View_HomeComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
    import0.ɵdid(49152,(null as any),0,import1.HomeComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HomeComponentNgFactory:import0.ComponentFactory<import1.HomeComponent> = import0.ɵccf('ng-component',import1.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvRGllZ28vRGVza3RvcC9hbmd1bGFyQ291cnNlL25vLWNsaWVudC1wcm9qZWN0L3NyYy9hcHAvaG9tZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvRGllZ28vRGVza3RvcC9hbmd1bGFyQ291cnNlL25vLWNsaWVudC1wcm9qZWN0L3NyYy9hcHAvaG9tZS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9EaWVnby9EZXNrdG9wL2FuZ3VsYXJDb3Vyc2Uvbm8tY2xpZW50LXByb2plY3Qvc3JjL2FwcC9ob21lLmNvbXBvbmVudC50cy5Ib21lQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9EaWVnby9EZXNrdG9wL2FuZ3VsYXJDb3Vyc2Uvbm8tY2xpZW50LXByb2plY3Qvc3JjL2FwcC9ob21lLmNvbXBvbmVudC50cy5Ib21lQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPlRoZSBob21lIHBhZ2U8L2gxPiIsIjxuZy1jb21wb25lbnQ+PC9uZy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUk7Ozs7OztJQ0FKO2dCQUFBOzs7OyJ9
